name: Use Secret Token
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use secret in env
        run: echo "The secret is $MY_SECRET_TOKEN"
        env:
          MY_SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
